import { Feather } from "@expo/vector-icons";
import { router } from "expo-router";
import React, { useState } from "react";
import {
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
  Alert,
  ActivityIndicator,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useApp } from "@/context/AppContext";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { LinearGradient } from "expo-linear-gradient";

const GREEN = "#10b981";
const GREEN_DARK = "#064e3b";
const WHITE = "#ffffff";

export default function RecoveryReportScreen() {
  const insets = useSafeAreaInsets();
  const { user, medicines, todayDoses, streak, xp } = useApp();
  const [generating, setGenerating] = useState(false);

  const adherence = todayDoses.length > 0 
    ? Math.round((todayDoses.filter(d => d.status === "taken").length / todayDoses.length) * 100)
    : 100;

  const generatePDF = async () => {
    try {
      setGenerating(true);
      
      const html = `
        <html>
          <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
            <style>
              body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #1e293b; }
              .header { border-bottom: 2px solid #10b981; padding-bottom: 20px; margin-bottom: 30px; }
              .title { font-size: 28px; color: #064e3b; margin: 0; }
              .subtitle { font-size: 14px; color: #64748b; margin-top: 5px; }
              .section { margin-bottom: 30px; }
              .section-title { font-size: 18px; font-weight: bold; margin-bottom: 15px; text-transform: uppercase; color: #10b981; }
              .stats-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px; }
              .stat-card { background: #f8fafc; padding: 15px; border-radius: 8px; border: 1px solid #e2e8f0; }
              .stat-val { font-size: 24px; font-weight: bold; color: #0f172a; }
              .stat-lab { font-size: 12px; color: #64748b; }
              table { width: 100%; border-collapse: collapse; }
              th { text-align: left; background: #f1f5f9; padding: 10px; font-size: 12px; }
              td { padding: 10px; border-bottom: 1px solid #e2e8f0; font-size: 13px; }
              .footer { margin-top: 50px; text-align: center; font-size: 10px; color: #94a3b8; }
            </style>
          </head>
          <body>
            <div class="header">
              <h1 class="title">Recovery Progress Report</h1>
              <div class="subtitle">Generated for ${user?.name || "Patient"} on ${new Date().toLocaleDateString()}</div>
            </div>

            <div class="stats-grid">
              <div class="stat-card">
                <div class="stat-val">${adherence}%</div>
                <div class="stat-lab">Overall Adherence</div>
              </div>
              <div class="stat-card">
                <div class="stat-val">${streak} Days</div>
                <div class="stat-lab">Current Streak</div>
              </div>
              <div class="stat-card">
                <div class="stat-val">${medicines.length}</div>
                <div class="stat-lab">Active Medications</div>
              </div>
              <div class="stat-card">
                <div class="stat-val">${xp} XP</div>
                <div class="stat-lab">Total Health Points</div>
              </div>
            </div>

            <div class="section">
              <div class="section-title">Medication Schedule</div>
              <table>
                <thead>
                  <tr>
                    <th>Medication</th>
                    <th>Dosage</th>
                    <th>Frequency</th>
                  </tr>
                </thead>
                <tbody>
                  ${medicines.map(m => `
                    <tr>
                      <td><strong>${m.name}</strong></td>
                      <td>${m.dosage}</td>
                      <td>${m.frequency}</td>
                    </tr>
                  `).join("")}
                </tbody>
              </table>
            </div>

            <div class="footer">
              This report is generated by Discharge Buddy. Always consult with your healthcare provider for medical decisions.
            </div>
          </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html });
      await Sharing.shareAsync(uri, { UTI: ".pdf", mimeType: "application/pdf" });
      
    } catch (err) {
      Alert.alert("Error", "Failed to generate report");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <View style={{ flex: 1, backgroundColor: WHITE }}>
      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={{ paddingBottom: insets.bottom + 32 }}
      >
        <View style={[styles.header, { paddingTop: insets.top + 12 }]}>
          <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
            <Feather name="arrow-left" size={20} color={WHITE} />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Recovery Report</Text>
          <View style={{ width: 36 }} />
        </View>

        <View style={styles.content}>
          <View style={styles.reportCard}>
            <View style={styles.reportIcon}>
              <Feather name="file-text" size={40} color={GREEN} />
            </View>
            <Text style={styles.reportTitle}>Monthly Summary</Text>
            <Text style={styles.reportDate}>March 2024</Text>
            
            <View style={styles.divider} />
            
            <View style={styles.statRow}>
              <View style={styles.stat}>
                <Text style={styles.statVal}>{adherence}%</Text>
                <Text style={styles.statLab}>Adherence</Text>
              </View>
              <View style={styles.vDivider} />
              <View style={styles.stat}>
                <Text style={styles.statVal}>{streak}</Text>
                <Text style={styles.statLab}>Day Streak</Text>
              </View>
              <View style={styles.vDivider} />
              <View style={styles.stat}>
                <Text style={styles.statVal}>{medicines.length}</Text>
                <Text style={styles.statLab}>Meds</Text>
              </View>
            </View>
          </View>

          <View style={styles.infoBox}>
            <Feather name="info" size={20} color="#065f46" />
            <Text style={styles.infoText}>
              Sharing this report with your doctor can help them better understand your recovery progress and medication adherence.
            </Text>
          </View>

          <TouchableOpacity 
            style={styles.actionBtn} 
            onPress={generatePDF}
            disabled={generating}
          >
            <LinearGradient
              colors={[GREEN, "#059669"]}
              style={styles.gradient}
            >
              {generating ? (
                <ActivityIndicator color={WHITE} />
              ) : (
                <>
                  <Feather name="share" size={20} color={WHITE} />
                  <Text style={styles.actionText}>Generate & Share PDF</Text>
                </>
              )}
            </LinearGradient>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  header: {
    backgroundColor: GREEN_DARK,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    color: WHITE,
    fontSize: 18,
    fontFamily: "Inter_700Bold",
  },
  content: {
    padding: 20,
    gap: 24,
  },
  reportCard: {
    backgroundColor: "#f0fdf4",
    borderRadius: 24,
    padding: 30,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#dcfce7",
  },
  reportIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: WHITE,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
    shadowColor: GREEN,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 5,
  },
  reportTitle: {
    fontSize: 20,
    fontFamily: "Inter_700Bold",
    color: "#064e3b",
  },
  reportDate: {
    fontSize: 14,
    color: "#059669",
    fontFamily: "Inter_500Medium",
    marginTop: 4,
  },
  divider: {
    width: "100%",
    height: 1,
    backgroundColor: "#dcfce7",
    marginVertical: 24,
  },
  statRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
  },
  stat: {
    alignItems: "center",
  },
  statVal: {
    fontSize: 22,
    fontFamily: "Inter_700Bold",
    color: "#064e3b",
  },
  statLab: {
    fontSize: 11,
    color: "#059669",
    fontFamily: "Inter_600SemiBold",
    textTransform: "uppercase",
    marginTop: 2,
  },
  vDivider: {
    width: 1,
    height: "100%",
    backgroundColor: "#dcfce7",
  },
  infoBox: {
    flexDirection: "row",
    padding: 16,
    backgroundColor: "#ecfdf5",
    borderRadius: 16,
    gap: 12,
  },
  infoText: {
    flex: 1,
    fontSize: 14,
    color: "#065f46",
    fontFamily: "Inter_400Regular",
    lineHeight: 20,
  },
  actionBtn: {
    borderRadius: 50,
    overflow: "hidden",
    shadowColor: GREEN,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 6,
  },
  gradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 18,
    gap: 10,
  },
  actionText: {
    color: WHITE,
    fontSize: 16,
    fontFamily: "Inter_700Bold",
  },
});
